client_config_backend: settings
client_config:
  client_id: 80750589138-p22fbvq8dr1os8oe0nq786or4np3bili.apps.googleusercontent.com
  client_secret: jv5HnmDtkzwI1pQuq25e456K

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install